import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const data = await req.json();

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const externalSupabaseUrl = Deno.env.get("EXTERNAL_SUPABASE_URL");
    const externalSupabaseKey = Deno.env.get("EXTERNAL_SUPABASE_SERVICE_ROLE_KEY");
    const externalSupabase = externalSupabaseUrl && externalSupabaseKey
      ? createClient(externalSupabaseUrl, externalSupabaseKey)
      : null;

    // Build insert data
    const insertData: Record<string, unknown> = {
      team_name: data.team_name,
      college_name: data.college_name,
      institute_number: data.institute_number,
      leader_name: data.leader_name,
      leader_email: data.leader_email,
      leader_phone: data.leader_phone,
      selected_problem_id: data.selected_problem_id || null,
      selected_domain: data.selected_domain || null,
      approach_description: data.approach_description || null,
      mentor_name: data.mentor_name,
      mentor_email: data.mentor_email,
      mentor_contact: data.mentor_contact,
    };

    // Add members
    const members = data.members || [];
    if (members[0]) {
      insertData.member2_name = members[0].name;
      insertData.member2_email = members[0].email;
      insertData.member2_role = members[0].role || null;
    }
    if (members[1]) {
      insertData.member3_name = members[1].name;
      insertData.member3_email = members[1].email;
      insertData.member3_role = members[1].role || null;
    }
    if (members[2]) {
      insertData.member4_name = members[2].name;
      insertData.member4_email = members[2].email;
      insertData.member4_role = members[2].role || null;
    }

    // Insert (team_id auto-generated by trigger)
    const { data: result, error } = await supabase
      .from("registered_teams")
      .insert(insertData)
      .select("team_id, team_name")
      .single();

    if (error) {
      console.error("Insert error:", error);
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Sync to external database
    if (externalSupabase && result) {
      try {
        const extInsert = { ...insertData, team_id: result.team_id };
        await externalSupabase.from("registered_teams").insert(extInsert);
        console.log("Team also saved to external database");
      } catch (extErr) {
        console.error("External DB sync error:", extErr);
      }
    }

    // Send confirmation email via Google Sheets or log
    // For now, log the registration
    console.log(`Team registered: ${result.team_id} - ${result.team_name}`);

    // Try to sync to Google Sheet
    try {
      const googleEmail = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_EMAIL");
      const googleKey = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY");
      const sheetId = Deno.env.get("GOOGLE_SHEET_ID");

      if (googleEmail && googleKey && sheetId) {
        console.log("Google Sheets sync would happen here for team:", result.team_id);
      }
    } catch (sheetErr) {
      console.error("Google Sheet sync error:", sheetErr);
    }

    return new Response(
      JSON.stringify({ success: true, team_id: result.team_id, team_name: result.team_name }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Edge function error:", error);
    return new Response(
      JSON.stringify({ error: "An error occurred during registration" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
